server:
  port: ${APPLICATION_PORT:8080}
  max-http-request-header-size: 128KB
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  tomcat:
    max-part-count: 100
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APPLICATION_NAME:banchus}
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    pe.nanamochi.banchus: ${LOG_LEVEL_BANCHUS:WARN}

banchus:
  menu-icon:
    image-url: ${MENU_ICON_IMAGE_URL}
    redirect-url: ${MENU_ICON_REDIRECT_URL}
  seasonal-backgrounds:
    urls: ${SEASONAL_BACKGROUND_URLS:}
  command-prefix: ${COMMAND_PREFIX:!}
  pp-calculator-type: ${PP_CALCULATOR_TYPE:osu-native}
  storage:
    type: ${STORAGE_TYPE:local}
    s3:
      bucket: ${S3_BUCKET:banchus-data}
      region: ${S3_REGION:us-east-1}
      endpoint: ${S3_ENDPOINT:}
      access-key: ${S3_ACCESS_KEY:}
      secret-key: ${S3_SECRET_KEY:}
  osu-api:
    v1:
      key: ${OSU_API_V1_KEY}