server:
    port: ${APPLICATION_PORT:8080}
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    pe.nanamochi.banchus: ${LOG_LEVEL_BANCHUS:WARN}

banchus:
  menu-icon:
    image-url: ${MENU_ICON_IMAGE_URL}
    redirect-url: ${MENU_ICON_REDIRECT_URL}
